services:
  backend:
    container_name: backend-container
    build:
      context: ./backend           # Directory del contesto di build
      dockerfile: Dockerfile      # Usa il Dockerfile specificato
    volumes:
      - backend_node_modules:/app/node_modules
    user: node
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/flightapp
    networks:
      - app-network

  frontend:
    container_name: frontend-container
    build: 
      context: ./frontend           # Directory del contesto di build
      dockerfile: Dockerfile      # Usa il Dockerfile specificato
    volumes:
      - frontend_node_modules:/app/node_modules
    ports:
      - "4200:4200"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    networks:
      - app-network
    depends_on:
      - backend
    
  mongo:
    build: 
      context: ./mongo           # Directory del contesto di build
      dockerfile: Dockerfile      # Usa il Dockerfile specificato  container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
  backend_node_modules:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge